services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    container_name: translator-client
    volumes:
      - ./client:/client
      - ./client/node_modules
