services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - NEXT_OUTPUT=production
    ports:
      - "3000:3000"
    container_name: translator-client

    volumes:
      - ./client:/client
