[package]
name = "translation_module"
version = "0.1.0"
edition = "2024"

[lib]
name = "translation_module"
crate-type = ["cdylib"]

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
pyo3 = { version = "0.20", features = ["extension-module"] }
