name: Build and Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./server/docs

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Sphinx HTML docs
        run: |
          export MONGO_URL=mongodb://localhost:27017/db
          export REDIS_URL=redis://localhost:6379
          export SECRET_KEY=dummy
          export DEBUG=False
          export ALLOWED_HOSTS=localhost
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./server/docs/build/html
