name: Rust Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: 1.85.0
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy (Rust Linter)
        run: cargo clippy -- -D warnings
